name: Run Targets Workflow and Publish to GitHub Pages

on:
  schedule:
    # Run at 8 PM every day
    - cron: "0 20 * * *"
  push:
    branches:
      - main  # You can specify other branches if needed

jobs:
  run_targets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: "4.2.1"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libharfbuzz-dev libfribidi-dev

    - name: Install Pandoc
      uses: r-lib/actions/setup-pandoc@v2
      with:
        pandoc-version: '2.11.4'

    - name: Install dependencies with renv
      run: |
        Rscript -e 'install.packages("renv")'
        Rscript -e 'renv::restore(packages = setdiff(renv::dependencies()$Package, "R.utils"))'


    - name: Run targets
      run: |
        Rscript -e 'targets::tar_make(cv_html)'

    - name: Move cv.html to root
      run: |
        mv cv.html index.html

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # Deploy from the root directory

    - name: Clean up
      run: |
        rm -rf docs
